# Generated by Django 5.2 on 2025-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0005_blog_background_image_url_blog_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
