# Generated by Django 5.2 on 2025-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0006_remove_blog_author_blog_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='background_image_url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_email',
            field=models.EmailField(blank=True, default='anonymous@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
