# Generated by Django 5.2 on 2025-04-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0012_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='Blog_Platform_App.blog'),
        ),
    ]
