# Generated by Django 5.2 on 2025-04-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0015_bookmark_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
