# Generated by Django 5.2 on 2025-04-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0020_dummyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyUser',
        ),
    ]
