# Generated by Django 5.2 on 2025-04-15 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0022_bookmark_created_at_alter_bookmark_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
