# Generated by Django 5.2 on 2025-04-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0023_alter_bookmark_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
