# Generated by Django 5.2 on 2025-04-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0027_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
