# Generated by Django 5.1.7 on 2025-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0032_blog_flask_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='flask_blog_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
