# Generated by Django 5.1.7 on 2025-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Platform_App', '0033_alter_blog_flask_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_by_django',
            field=models.BooleanField(default=False),
        ),
    ]
